apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Demo API Management"
  labels:
    kubernetes.io/metadata.name: {{ .Values.projectName | quote }}
  name: {{ .Values.projectName | quote }}
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: {{ .Values.projectName | quote }}
  namespace: {{ .Values.projectName | quote }}
spec:
  targetNamespaces:
  - {{ .Values.projectName | quote }}
