apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Microcks"
  labels:
    kubernetes.io/metadata.name: microcks
  name: microcks
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: microcks
  namespace: microcks
spec:
  targetNamespaces:
  - microcks
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: microcks
  namespace: microcks
spec:
  channel: stable
  name: microcks
  source: community-operators
  sourceNamespace: openshift-marketplace
