apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Single Sign On"
  labels:
    kubernetes.io/metadata.name: sso
  name: sso
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: sso
  namespace: sso
spec:
  targetNamespaces:
  - sso
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: rhsso-operator
  namespace: sso
spec:
  channel: stable
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
